PROGNAME = calibrationhost
SRCS = calibrationhost.c

CFLAGS = -g

LDFLAGS += -llinalg -lcalibration -lm

DATALIBS = ../calibration/calibration.da

include ../make/datagen.mk
include ../make/app.mk
include ../make/host.mk
