SUBDIRS = commusbhost   echo       firstdata  firstmag          hackadc     sca3000 \
	  cavedump     datahosttest  eememtest  firstint   firsttimer        hmc105x  \
	  testdac commusb      debug         firstadc   firstlcd   firstusb          \
          lcdnegtest  uartfs commusbfast  dualusb       firstbatt  firstled  \
          firstusbloadable  libusbtest 

include ../make/subdir.mk

