/* Copyright (C) 2008 Sean D'Epagnier <sean@depagnier.com>
 *
 * This Program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * For more information on the GPL, please go to:
 * http://www.gnu.org/copyleft/gpl.html
 */

/* this program reads in files in reader rich text format from stdin
   and outputs readertext.c and readertext.h */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#include "../reader.h"

FILE *source, *header;

uint8_t lastattribs, attribs;
uint8_t done;

void showchar(char c);

void set_size(int num) { attribs = attribs & ~SIZE_MASK | num; }
#define MAKE_SIZE(X) void size##X(void) { set_size(X); }
MAKE_SIZE(0) MAKE_SIZE(1) MAKE_SIZE(2) MAKE_SIZE(3)
MAKE_SIZE(4) MAKE_SIZE(5)
void set_alignment(int num) { attribs = attribs & ~ALIGNMENT_MASK | num; }
void left(void) { set_alignment(LEFT); }
void right(void) { set_alignment(RIGHT); }
void center(void) { set_alignment(CENTER); }
void justify(void) { set_alignment(JUSTIFY); }
void name(void) { done = 1; }

struct control {
   char *name;
   void (*thunk)(void);
};

#define CTR(name) {#name, name}

struct control controls[] = {CTR(size0), CTR(size1), CTR(size2), CTR(size3),
                             CTR(size4), CTR(size5),
                             CTR(left), CTR(right), CTR(center), CTR(justify),
                             CTR(name)};

void showchar(char c)
{
   /* break lines after every 100 characters
      (sometimes gcc complains about lines longer than 1024) */
   static int linebreak;
   if(linebreak++ > 100) {
       fputc('\n', source);
       linebreak = 0;
   }

   if(attribs != lastattribs) {
      lastattribs = attribs;
      fprintf(source, "0x%hhx, ", attribs | CONTROL);
   }

   /* to make it easier to read */
   if(c >= ' ' && c < 126 && c != '\'')
      fprintf(source, "'%c',", c);
   else
      fprintf(source, "0x%x,", c);
}

void parsetext(void)
{
   int c;
   done = 0;
 again:
   c = getchar();
 again1:
   if(c == EOF)
      return;

   if(c != '@') {
      showchar(c);
      goto again;
   }
   
   c = getchar();
   switch(c) {
   case 0:
      fprintf(stderr, "error, @ at end of t\n");
      return;
   case '@':
      showchar('@');
      goto again;
   }

   char control[256];
   int len = 0;
   for(;;) {
      control[len++] = c;
      c = getchar();
      if(c == ' ' || c == '\n')
         break;
      if(c == EOF) {
         fprintf(stderr, "unexpected eof\n");
         return;
      }
   }
   control[len] = 0;

   /* execute the control */
   int i;
   for(i = 0; i<(sizeof controls) / (sizeof *controls); i++)
      if(!strcmp(controls[i].name, control)) {
         controls[i].thunk();
         if(done)
            return;
         if(c == '\n')
            goto again1;
         goto again;
      }

   fprintf(stderr, "control %s not found\n", control);
   goto again;
}

int main(void)
{
   /* open files */
   if(!(source = fopen("readertext.c", "w"))) {
      fprintf(stderr, "Failed to open readertext.c\n");
      exit(1);
   }
   fprintf(source, "/* This file generated by readerparser */\n");
   fprintf(source, "#include <avrdata.h>\n");
   fprintf(source, "#include \"reader.h\"\n");

   if(!(header = fopen("readertext.h", "w"))) {
      fprintf(stderr, "Failed to open readertext.h\n");
      exit(1);
   }

   fprintf(header, "/* This file generated by readerparser */\n");
   fprintf(header, "#include \"reader.h\"\n");

   char name[7] = {0};
   if(fread(name, 6, 1, stdin) != 1 || strcmp(name, "@name "))
      fprintf(stderr, "File should start with @name\n");

   /* main loop */
   for(;;) {
      /* read until colon */
      char name[1024];
      int i = 0;
      for(;;) {
         int c = getchar();
         if(c == EOF)
            exit(0);
         if(c == '\n')
            break;
         name[i++] = c;
      }
      name[i] = 0; /* null terminate */
      lastattribs = attribs = DEFAULT_ATTRIBS;

      fprintf(header, "extern const char %s[];\n", name);
      fprintf(source, "const char %s[] PROGMEM = {\n", name);
      parsetext();
      fprintf(source, "0};\n\n");
   }
}
