LIBNAME=calibration
SRCS=calc.c fit.c sensor.c calaccel.c calmag.c temperature.c filter.c still.c compute.c show.c

CFLAGS += -DF_CPU=8000000UL -DNDEBUG

MULTILIBDATAGEN=1

include ../make/multilib.mk
